---
- hosts: all

  vars_files:
    - ../../vault_secrets.yml

  vars_prompt:
    - name: user_account
      prompt: "name for future user account"
      private: no
    - name: user_password
      prompt: "password for account"
      confirm: yes
      private: yes
      encrypt: "sha512_crypt"

  roles:
    - arch_system_installation_preinst
    - arch_system_installation_postinst
