---
- name: Install yay - AUR
  shell: |
    sudo -u {{ user_account }} mkdir -p ".local/yay"
    sudo -u {{ user_account }} git clone https://aur.archlinux.org/yay.git
    sudo -u {{ user_account }} -D ".local/yay" makepkg --noconfirm -si

