---
- name: Allow users from wheel to execute as sudo
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "%wheel ALL=(ALL:ALL) ALL"
    line: "%wheel ALL=(ALL:ALL) ALL"
    state: present

- name: Create {{ user_account }} account
  user:
    name: "{{ user_account }}"
    group: wheel
    comment: "{{ user_account }}"
    password: "{{ user_password }}"

- name: Check if vault_secrets.yml exists
  delegate_to: localhost
  become: false
  stat:
    path: ~/opt/ansible/vault_secrets.yml
  register: secrets

- name: Create tehnical account
  block:
    - name: Include the vault file
      include_vars:
        file: ~/opt/ansible/vault_secrets.yml

    - name: Create tehnical accounts
      no_log: true
      user:
        name: "{{ item.key }}"
        group: wheel
        comment: "{{ item.value.comment }}"
        password: "{{ item.value.password | password_hash('sha512') }}"
      loop: "{{ vault_accounts | dict2items}}"
  when: secrets.stat.exists
