---
- name: Allow users from wheel to execute as sudo
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "%wheel ALL=(ALL:ALL) ALL"
    line: "%wheel ALL=(ALL:ALL) ALL"
    state: present

- name: "Create {{ user_account }} account"
  user:
    name: "{{ user_account }}"
    group: wheel
    comment: "{{ user_account }}"
    password: "{{ user_password }}"

- name: "Create ansible account"
  user:
    name: ansible
    group: wheel
    comment: tehnical account
    password: '$6$k.eEaNXmtjuxPrR0$U5bRdrW5tJoH6p8ASkD8A9Qsl1KvSb0DXwhtVt5Qr6hRsBMSfrntdGJS9lzyL0JJEetCWQiEXmB'
