---
- name: Main block
  block:
    - name: Installing additional packages
      include_tasks: 010_additional_packages.yml

    - name: Configuring system
      include_tasks: 020_configuration.yml

    - name: Installing suckless programs
      include_tasks: 030_suckless_progs.yml
      loop: "{{ suckless_progs }}"
      loop_control:
        loop_var: suckless_progs_element

    - name: Modify the user from configs
      shell: >
        find /home/{{ user_account }}/ -type f | xargs sed -i "s|arghpy|{{ user_account }}|g"

    - name: Change {{ user_account }} shell
      user:
        name: "{{ user_account }}"
        shell: /usr/bin/zsh
