---
- name: Cloning the configuration repository
  git:
    repo: "{{ githubRepo }}{{ dotfiles }}"
    dest: "/home/{{ user_account }}/dotfiles"
  register: result
  until: result.failed == False
  retries: 5
  delay: 3


- name: Copy config
  copy:
    src: "/home/{{ user_account }}/{{ dotfiles }}/"
    dest: "/home/{{ user_account }}/"
    remote_src: yes
    owner: "{{ user_account }}"
    group: wheel

- name: Remove cloned directory
  file:
    path: "/home/{{ user_account }}/{{ dotfiles }}/"
    state: absent
