---
- name: Enable sshd service
  file:
    src: /mnt/usr/lib/systemd/system/sshd.service
    dest: /mnt/etc/systemd/system/multi-user.target.wants/sshd.service
    state: link

- name: Enable NetworkManager service
  file:
    src: /mnt/usr/lib/systemd/system/NetworkManager.service
    dest: /mnt/etc/systemd/system/multi-user.target.wants/NetworkManager.service
    state: link
