---
- name: Cloning nvim
  git:
    repo: "{{ githubRepo }}nvim"
    dest: "/home/{{ user_account }}/.config/"
  register: result
  until: result.failed == False
  retries: 5
  delay: 3

- name: Change ownership of config directory
  file:
    path: "/home/{{ user_account }}/.config"
    owner: "{{ user_account }}"
    group: wheel
    recurse: yes

- name: Prepare packer for nvim
  shell: su - {{ user_account }} -c "bash /home/{{ user_account }}/.config/nvim/install_packer.txt"
