---
- name: Copy the template on the machine
  template:
    src: "dconf_settings.j2"
    dest: "/home/{{ user_account }}/dconf_settings"
    owner: "{{ user_account }}"
    group: "{{ user_account }}" 
    mode: '0744'

- name: Load the configuration as {{ user_account }}
  shell: su - {{ user_account }} -c "dbus-launch dconf load /org/gnome/ < /home/{{ user_account }}/dconf_settings"

- name: Remove dconf_settings
  file:
    path: "/home/{{ user_account }}/dconf_settings"
    state: absent
