---
- name: Main block
  block:
    - name: Setting up python3 for ansible
      include_tasks: 050_python_setup.yml

    - name: Installing additional packages
      include_tasks: 020_additional_packages.yml

    - name: Install git repos
      include_tasks: 030_git_install.yml

    - name: Change {{ user_account }} shell
      user:
        name: "{{ user_account }}"
        shell: /usr/bin/zsh

    - name: Add zsh configuration
      template:
        src: "zshrc.j2"
        dest: "/home/{{ user_account }}/.zshrc"
        owner: "{{ user_account }}"
        group: "{{ user_account }}" 
        mode: '0744'

    - name: Setting up time
      include_tasks: 09_set_time.yml
          
    - name: Manage networking
      include_tasks: 040_manage_network.yml

    - name: Enabling services
      include_tasks: 060_enable_services.yml
      loop: "{{ services }}"
      loop_control:
        loop_var: service_element

    - name: Customize system through dconf
      include_tasks: 070_dconf_setup.yml

    - name: Add admin group and manage rights
      include_tasks: 080_admin_group.yml

    - name: Add Downloads directory for {{ user_account }}
      file:
        path: "/home/{{ user_account }}/Downloads"
        state: directory
        owner: "{{ user_account }}"
        group: wheel

    - name: Update the system
      shell: xbps-install -Syu
        
    - name: Credentials
      debug:
        msg: "The password for the root account is root. Please change it!"

    - name: Reboot the system
      reboot:
        reboot_timeout: 5
      ignore_errors: true
      ignore_unreachable: true
