---
- name: Installing grub
  shell: "xchroot /mnt xbps-install -y grub-x86_64-efi"

- name: Configuring grub
  shell: xchroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id="Void"
