---
- name: Allow users from wheel to execute as sudo
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "%wheel ALL=(ALL:ALL) ALL"
    line: "%wheel ALL=(ALL:ALL) ALL"
    state: present

- name: Create {{ user_account }} account
  user:
    name: "{{ user_account }}"
    group: wheel
    comment: "{{ user_account }}"
    password: "{{ user_password }}"

- name: Add bashrc
  template:
    src: "bashrc.j2"
    dest: "/home/{{ user_account }}/.bashrc"
    owner: "{{ user_account }}" 
    mode: '0744'

- name: Create tehnical accounts
  user:
    name: "{{ item.key }}"
    group: wheel
    comment: "{{ item.value.comment }}"
    password: "{{ item.value.password | password_hash('sha512') }}"
  loop: "{{ vaultAccounts | dict2items }}"
